### ISSUE TITLE
Dataset packages problem

### ISSUE THREAD

**Issue by ssmem** [Jinghe-mel/UFEN-SLAM#1]
I have downloaded the dataset. After extracting files from zip, I found Heavy-10/Heavy-09/Heavy-07/cum08, Heavy-09/Heavy-10/Heavy-07/cum08, Heavy-06/cum06, Heavy-08/Heavy-07/cum08, Heavy-07/cum08. Can you check it?

**Comment by Jinghe-mel** [comment]
Thank you for your reminder.
The files have been updated.
