### ISSUE TITLE
Can't get access to the dataset

### ISSUE THREAD

**Issue by zzC1oudy** [Jinghe-mel/UFEN-SLAM#2]
The website hosting the dataset seems to be decomissioned and I can't download the dataset. Will it be updated? By the way, I wonder if the code of UFEN would be public recently.

**Comment by Jinghe-mel** [comment]
Will update the new sharing link by the end of this week. 
As still doing the extension for a Journal paper, the code and the model hopefully will be public together in 2-3 months.

**Comment by zzC1oudy** [comment]
I know. Thank you for your reply!

**Comment by Jinghe-mel** [comment]
Hi, the data link has been updated.
Regards,

**Comment by zzC1oudy** [comment]
Thank you! I can see the dataset now.
