### ISSUE TITLE
Raw dataset

### ISSUE THREAD

**Issue by fickrie67** [Jinghe-mel/UFEN-SLAM#3]
Hi, can i get the raw MP4 file for the dataset?, hence i want to integrate imu measurements too..thanks!

**Comment by Jinghe-mel** [comment]
Hi, I am unsure if the .MP4 files include IMU measurements. Additionally, I have not calibrated the camera with the IMU. 
But, I will provide an example video for you to try by next week on Huggingface. 
Please let me know if this is helpful, and I will tidy up and upload the remaining files accordingly.

**Comment by Jinghe-mel** [comment]
It is available right now.
Regards,

**Comment by fickrie67** [comment]
Hi, thanks a lot for providing the MP4 dataset! I see that it is in the heavy scenario, would you also mind providing the example in the clear scenario?  Also, I see that according to the paper, the dataset has been downsampled. would you also mind to provide the raw MP4 before it was downsampled? or maybe it is too big for the size? anyway, thanks a lot it is such a great dataset!

**Comment by Jinghe-mel** [comment]
No worries. And thank you for your interest in the dataset.
I have uploaded the Clear-02.MP4 file to Hugging Face. I think the videos have been only processed by GoPro without downsampling, resulting in a frame width/height of 4000/3000 pixels.

**Comment by fickrie67** [comment]
Well noted. Thanks!
